set linesize 200 pagesize 2000
col CURRENT_SCN for 99999999999999
col STANDBY_BECAME_PRIMARY_SCN for 9999999999999999
col INSTANCE for a10
SELECT DATABASE_ROLE, DB_UNIQUE_NAME INSTANCE, OPEN_MODE, PROTECTION_MODE, PROTECTION_LEVEL, SWITCHOVER_STATUS ,CURRENT_SCN,STANDBY_BECAME_PRIMARY_SCN from  v$database ;

select thread#,max(sequence#) from v$archived_log where RESETLOGS_CHANGE#=(SELECT  MAX(RESETLOGS_CHANGE#) FROM v$archived_log ) group by thread#;   

